"""ajouter la table commande 

Revision ID: 8f3426fa4ea5
Revises: c9c9d0f6c4e3
Create Date: 2025-05-21 09:11:45.034088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f3426fa4ea5'
down_revision = 'c9c9d0f6c4e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commande',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.Column('etat_commande', sa.String(length=250), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('produit_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['produit_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('commande')
    # ### end Alembic commands ###
